### PR TITLE
Add support of standalone & fix SSR error

### PR DESCRIPTION
**Pull request by zip-fa**
What has been done here:

1) Added standalone components support
2) Enabled strict mode everywhere (demo-app & chart component)
3) Converted demo app fully to standalone
4) Bumped Angular peerDependency to v14 (which is not supported too, but will be backward-compatible & non-breaking)
5) Fixed SSR error because of window.ApexCharts call

### CODE REVIEW

**Comment by zip-fa** [comment]
@junedchhipa README.md must be updated and cover standalone topic. That's what I didn't do.

**Comment by zip-fa** [comment]
i've added lazy-loading and full support of v17 angular and application builder out-of-the-box.
This shaved much weight from resulting build.

For those who want to check this out before my PR is accepted, please give it a try: https://www.npmjs.com/package/ng-apexcharts-lazy

**Comment by zip-fa** [comment]
That's how much KBs got shaved!

image

**Comment by junedchhipa** [comment]
Hey @zip-fa 
Please update the README as well to cover the important topics you've updated in this PR.

**Comment by BeSaRa** [comment]
any update about this PR because of SSR issue ?

**Review by junedchhipa — APPROVED** [review]

**Comment by junedchhipa** [comment]
Hey @zip-fa 
Merging this PR caused a lot of issues (maybe because I missed something while fixing conflicts). I have reverted these changes. Feel free to create a new PR so I can review again.
Thanks

**Pull request merged**
