### PR TITLE
remove deep imports

### LINKED ISSUE #72: Angular Ivy compiler warning
Angular compiler shows warning:
```
Warning: Entry point 'ng-apexcharts' contains deep imports into 'C:/test/node_modules/apexcharts/dist/apexcharts.esm.js'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

Possible places:
https://github.com/apexcharts/ng-apexcharts/blob/master/projects/ng-apexcharts/src/lib/ng-apexcharts.module.ts#L3

https://github.com/apexcharts/ng-apexcharts/blob/master/projects/ng-apexcharts/src/lib/chart/chart.component.ts#L34

### PR DESCRIPTION
**Pull request by mokeev1995**
Fixed #72

### CODE REVIEW

**Comment by junedchhipa** [comment]
Would this load apexcharts from `apexcharts/dist/apexcharts.min.js` or `apexcharts/dist/apexcharts.esm.js`.
As `esm import` is causing currently.

**Comment by mokeev1995** [comment]
image

As far as I can tell, unfortunately it uses esm module

**Comment by junedchhipa** [comment]
You're right, that's where it is defined. I missed that because it was done by a contributor months ago.

Now, the issue is that ESM-build currently doesn't expose the correct ApexCharts variable, and hence breaks everything (as mentioned in this [issue](https://github.com/apexcharts/apexcharts.js/issues/1760)).

The current UMD build `dist/apexcharts.min.js` works everywhere and is less problematic. Hence, I am thinking of removing the `module` field from package.json. Then, we need to figure out why UMD build causes deep imports.

**Comment by mokeev1995** [comment]
@junedchhipa i can try to figure out what is going on with esm build.

the reason why angular ivy compiler complains about deep imports is simple: 'cause there's DEEP IMPORT 
```js
import ApexCharts from 'apexcharts/dist/apexcharts.min.js';
```
to `apexchart` lib, not just 
```js
import ApexCharts from 'apexcharts';
```

So, the solution is also simple - remove deep import.

**Comment by junedchhipa** [comment]
Ok, so in that case, I will remove the `module` field from package.json and keep `apexcharts.min.js` as the default file.
This way, we can avoid deep imports.

**Comment by sp90** [comment]
I think it might have been me on the 'esm' part I got it to work back when I built it but might have missed some particular problems.

Anyway if you need help to resolve this, you're more than welcome to reach out

**Comment by mokeev1995** [comment]
@sp90 the solution for `@angular/cli` warning was successfully found and fixed it in this PR. 
Nothing else can fix that warning, I suppose. Correct me if I'm wrong.

**Comment by sp90** [comment]
@mokeev1995 it seems like your right

**Pull request merged**
