### PR TITLE
build: bump angular 13

### LINKED ISSUE #171: Support for Angular 13
As Angular 13 has been released, is it possible to release a new version with updated dependencies? I've been running it using -force flag and it seems to work.

Thanks!

### PR DESCRIPTION
**Pull request by damingerdai**
Close #171

### CODE REVIEW

**Comment by tuuling** [comment]
This would be very good to have. Since currently with angular13 unit tests that include ng apexcharts break due to Ivy not implemented (I assume).

```
 Unexpected value 'NgApexchartsModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.
      31 |
      32 |     beforeEach(() => {
    > 33 |         fixture = TestBed.createComponent(DashboardComponent);
```

**Comment by damingerdai** [comment]
@tuuling please review agagin

**Comment by tuuling** [comment]
@damingerdai   Sorry, I guess I was a bit vague. The error I get is with the current latest relase of ng-apexcharts. I was hoping the pull request you made will fix this, as it removes 
`"enableIvy": false`

Angular 13 dropped support for View Engine, so all the things packaged for it should use Ivy.
[https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296](https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296)
> State of View Engine
View Engine is no longer available in Angular as of v13.

**Comment by damingerdai** [comment]
> @damingerdai Sorry, I guess I was a bit vague. The error I get is with the current latest relase of ng-apexcharts. I was hoping the pull request you made will fix this, as it removes `"enableIvy": false`
> 
> Angular 13 dropped support for View Engine, so all the things packaged for it should use Ivy. https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296
> 
> > State of View Engine
> > View Engine is no longer available in Angular as of v13.

i had removed `"enableIvy": false` in this pr. bedside, i also make sure the `ng test ng-apexcharts` command pass

**Comment by sandrooco** [comment]
Is there anything I could do to help this getting further? I know that there are workarounds but it's still not wrong to keep up to date with Angular's releases.

**Comment by damingerdai** [comment]
> Can we also move to RxJs 7? Maybe a version change to 2.0 instead of 1.7 for the breaking change.

angular 13 still supports rxjs6

**Comment by Jalgoczy** [comment]
Is it good? Can somebody merge this?

**Pull request merged**
